name: CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Dependency Resolution
        run: yarn install
        
      - name: PRISMA intergrate
        run: |  
          yarn prisma generate,
          
      - name: API
        run: yarn start api
      
      - name: Client
        run: yarn start client
